<div style="margin-top: 20px; font-size: 18px;">
					<p class="text11">Do you want to add the website as a <span class="text_member">member</span> or as <span class="text_visitor">visitor</span> ?</p><br>
					<button class="btn1" id="login_as_member"><a href="#">Member</a></button><button class="btn1" style="background: #ff9d26; margin-left: 20px;"><a href="add_website.html">Visitor</a></button>
					<div class="both"></div>
				</div>

				<div class="wrapper m_area" id="member_login">
					<div class="form_title">
						<i style="background-position: -36px; 0px;"></i><h2>Member Login</h2>
					</div>
						<?php echo $this->form?>
					<div class="both"></div>					
				</div>
