<span class="text4">* Required fields</span>
				<form id="registerWidtAccLeft"  class="login_form" action="<?php echo $this->element->getAction(); ?>"   method="<?php echo $this->element->getMethod(); ?>">
						<div class="row2">
							<?php echo $this->element->getElement('name')?><i style="background-position: -2px -20px;"></i>
						</div>
						<div class="row2 right">
							<?php echo $this->element->getElement('login')?><i style="background-position: -2px -20px;"></i>
						</div>
						<div class="row2">
							<?php echo $this->element->getElement('pass')?><i style="background-position: -2px -1px;"></i>
						</div>
						<div class="row2 right">
							<?php echo $this->element->getElement('pass2')?><i  style="background-position: -2px -1px;"></i>
						</div>
						<div class="row2">
							<?php echo $this->element->getElement('email')?><i style="background-position: -2px -39px;"></i>
						</div>
						<div class="row2 right">
							<?php echo $this->element->getElement('email2')?><i style="background-position: -2px -39px;"></i>
						</div>
						<div class="both"></div>
						<div class="bottom_reg">
							<?php echo $this->element->getElement('cap')?>
							<i></i><button class="btn3" style="margin-right: 0 !important; margin-top: 0 !important; width: 90px"><i></i>Register</button>
						</div>
				</div>