		<article id="advantages">
			<div class="advantage"><i style="background-position: -2px -2px;"></i>The <span class="bold">Best</span> websites</div>
			<div class="advantage"><i style="background-position: -34px -2px;"></i>The <span class="bold">Moderate</span> websites</div>
			<div class="advantage"><i style="background-position: -64px -2px;"></i>The <span class="bold">Worst</span> websites</div>
		</article>

		<div class="both"></div>

		<section id="content">
				<?php echo $this->searchHtml()?>
		</section>	

		<aside id="right-column">
			<div id="add-site-btn">
				<a href="/add" class="add-site-btn">Add new Website</a><span class="add-icon"></span>
			</div>
		</aside>
		<div class="both"></div>
		
		<div id="big_banner">
			<img src="images/banner1.png" alt="">
		</div>
	
