<section id="content">
<?php echo $this->searchHtml()?>
				<ul class="breadcrumbs">
					<li>
						Index
					</li>
					<li class="angle-right"></li>
					<li>Add new Website</li>
				</ul>

				<div class="wrapper">
					<div class="form_title">
						<i></i><h2>Website Details</h2>
					</div>
					<?php echo $this->form?>
				</div>
					</section>	

		<aside id="right-column">
			<div id="add-site-btn">
				<button class="add-site-btn">Add new Website</button><span class="add-icon"></span>
			</div>
			<div id="ad_block1">BANNER</div>
			<div id="ad_block2">BANNER</div>
			<div id="ad_block3">BANNER</div>
			<div id="ad_block4">BANNER</div>
		</aside>