<div class="popup-login" id="popup-login">
				
				<div class="form_title">
					<i></i><h2>User Login</h2><i class="f_close"></i>
				</div>
				<div class="login_form">
				<?php echo $this->form?>
				<div class="login_with_socials right">
						<ul>
							<li class="btn2 soc_vk_btn">Войти с Вконтакте <i class="soc_vk_ico"></i></li>
							<li class="btn2 soc_fb_btn">Войти с facebook <i class="soc_fb_ico"></i></li>
							<li class="btn2 soc_tw_btn">Войти с twitter <i class="soc_tw_ico"></i></li>
							<li class="btn2 soc_gl_btn">Войти с google <i class="soc_gl_ico"></i></li>
						</ul>
					</div>
					
				</div>
			</div>
