<fieldset id="search">
					<input type="text" placeholder="Search for a website" class="search_field" id="searchValue"/><span class="search-icon"></span>
				</fieldset>
				<div class="search-example">eg. www.exnethellas.gr</div>

				<div id="search-results">
					<div class="result-rows">
						
					</div>
					<div class="no-results">
						<span>There is no such website. Do you want to add website?</span>
						<span><a href="#">Add</a>new website</span>
					</div>
				</div>